[package]
name = "rockbox-audio"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
anyhow.workspace = true
lazy_static = "1.5.0"
rodio = "0.20.1"
