name: release
on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish"
        type: "string"
        required: true
  pull_request:

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build and upload release
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.tag || github.ref_name }}
